/* tslint:disable: object-literal-key-quotes object-literal-sort-keys*/
export const matchDetailsMock = {
  generated_at: "2019-07-27T09:57:47+00:00",
  schema:
    "http://schemas.sportradar.com/bsa/soccer/v1/json/endpoints/soccer/match_summary.json",
  sport_event: {
    id: "sr:match:14735957",
    scheduled: "2018-08-10T19:00:00+00:00",
    start_time_tbd: false,
    tournament_round: {
      type: "group",
      number: 1,
      phase: "regular season",
    },
    season: {
      id: "sr:season:54571",
      name: "Premier League 18/19",
      start_date: "2018-08-10",
      end_date: "2019-05-13",
      year: "18/19",
      tournament_id: "sr:tournament:17",
    },
    tournament: {
      id: "sr:tournament:17",
      name: "Premier League",
      sport: {
        id: "sr:sport:1",
        name: "Soccer",
      },
      category: {
        id: "sr:category:1",
        name: "England",
        country_code: "ENG",
      },
    },
    competitors: [
      {
        id: "sr:competitor:35",
        name: "Manchester United",
        country: "England",
        country_code: "ENG",
        abbreviation: "MNU",
        qualifier: "home",
      },
      {
        id: "sr:competitor:31",
        name: "Leicester City",
        country: "England",
        country_code: "ENG",
        abbreviation: "LEI",
        qualifier: "away",
      },
    ],
    venue: {
      id: "sr:venue:9",
      name: "Old Trafford",
      capacity: 75635,
      city_name: "Manchester",
      country_name: "England",
      map_coordinates: "53.463150,-2.291444",
      country_code: "ENG",
    },
  },
  sport_event_conditions: {
    referee: {
      id: "sr:referee:52261",
      name: "Marriner, Andre",
      nationality: "England",
      country_code: "ENG",
    },
    referee_assistants: [
      {
        type: "first_assistant_referee",
        id: "sr:referee:79890",
        name: "Ledger, Scott",
        nationality: "England",
        country_code: "ENG",
      },
      {
        type: "second_assistant_referee",
        id: "sr:referee:88710",
        name: "Long, Simon",
        nationality: "England",
        country_code: "ENG",
      },
    ],
    venue: {
      id: "sr:venue:9",
      name: "Old Trafford",
      capacity: 75635,
      city_name: "Manchester",
      country_name: "England",
      map_coordinates: "53.463150,-2.291444",
      country_code: "ENG",
    },
    attendance: 74439,
    weather_info: {
      pitch: "good",
      weather_conditions: "good",
    },
  },
  sport_event_status: {
    status: "closed",
    match_status: "ended",
    home_score: 2,
    away_score: 1,
    winner_id: "sr:competitor:35",
    period_scores: [
      {
        home_score: 1,
        away_score: 0,
        type: "regular_period",
        number: 1,
      },
      {
        home_score: 1,
        away_score: 1,
        type: "regular_period",
        number: 2,
      },
    ],
  },
  statistics: {
    teams: [
      {
        id: "sr:competitor:35",
        name: "Manchester United",
        abbreviation: "MNU",
        qualifier: "home",
        statistics: {
          ball_possession: 46,
          shots_blocked: 1,
          shots_on_target: 6,
          throw_ins: 19,
          fouls: 11,
          goal_kicks: 7,
          shots_saved: 3,
          free_kicks: 9,
          offsides: 4,
          corner_kicks: 2,
          shots_off_target: 1,
          injuries: 1,
          yellow_cards: 2,
        },
        players: [
          {
            id: "sr:player:69378",
            name: "De Gea, David",
            substituted_in: 0,
            substituted_out: 0,
            goals_scored: 0,
            assists: 0,
            own_goals: 0,
            yellow_cards: 0,
            yellow_red_cards: 0,
            red_cards: 0,
          },
          {
            id: "sr:player:19352",
            name: "Darmian, Matteo",
            substituted_in: 0,
            substituted_out: 0,
            goals_scored: 0,
            assists: 0,
            own_goals: 0,
            yellow_cards: 0,
            yellow_red_cards: 0,
            red_cards: 0,
          },
          {
            id: "sr:player:606346",
            name: "Bailly, Eric",
            substituted_in: 0,
            substituted_out: 0,
            goals_scored: 0,
            assists: 0,
            own_goals: 0,
            yellow_cards: 0,
            yellow_red_cards: 0,
            red_cards: 0,
          },
          {
            id: "sr:player:143334",
            name: "Lindelof, Victor",
            substituted_in: 0,
            substituted_out: 0,
            goals_scored: 0,
            assists: 0,
            own_goals: 0,
            yellow_cards: 0,
            yellow_red_cards: 0,
            red_cards: 0,
          },
          {
            id: "sr:player:190839",
            name: "Shaw, Luke",
            substituted_in: 0,
            substituted_out: 0,
            goals_scored: 1,
            assists: 0,
            own_goals: 0,
            yellow_cards: 0,
            yellow_red_cards: 0,
            red_cards: 0,
          },
          {
            id: "sr:player:243623",
            name: "Fred",
            substituted_in: 0,
            substituted_out: 1,
            goals_scored: 0,
            assists: 0,
            own_goals: 0,
            yellow_cards: 1,
            yellow_red_cards: 0,
            red_cards: 0,
          },
          {
            id: "sr:player:285949",
            name: "Pereira, Andreas",
            substituted_in: 0,
            substituted_out: 0,
            goals_scored: 0,
            assists: 0,
            own_goals: 0,
            yellow_cards: 1,
            yellow_red_cards: 0,
            red_cards: 0,
          },
          {
            id: "sr:player:111802",
            name: "Pogba, Paul",
            substituted_in: 0,
            substituted_out: 1,
            goals_scored: 1,
            penalty_goals_scored: 1,
            assists: 0,
            own_goals: 0,
            yellow_cards: 0,
            yellow_red_cards: 0,
            red_cards: 0,
          },
          {
            id: "sr:player:34120",
            name: "Sanchez, Alexis",
            substituted_in: 0,
            substituted_out: 0,
            goals_scored: 0,
            assists: 0,
            own_goals: 0,
            yellow_cards: 0,
            yellow_red_cards: 0,
            red_cards: 1,
          },
          {
            id: "sr:player:903830",
            name: "Rashford, Marcus",
            substituted_in: 0,
            substituted_out: 1,
            goals_scored: 0,
            assists: 0,
            own_goals: 0,
            yellow_cards: 0,
            yellow_red_cards: 0,
            red_cards: 0,
          },
          {
            id: "sr:player:28367",
            name: "Mata, Juan",
            substituted_in: 0,
            substituted_out: 0,
            goals_scored: 0,
            assists: 1,
            own_goals: 0,
            yellow_cards: 0,
            yellow_red_cards: 0,
            red_cards: 0,
          },
          {
            id: "sr:player:78893",
            name: "Lukaku, Romelu",
            substituted_in: 1,
            substituted_out: 0,
            goals_scored: 0,
            assists: 0,
            own_goals: 0,
            yellow_cards: 0,
            yellow_red_cards: 0,
            red_cards: 0,
          },
          {
            id: "sr:player:908372",
            name: "McTominay, Scott",
            substituted_in: 1,
            substituted_out: 0,
            goals_scored: 0,
            assists: 0,
            own_goals: 0,
            yellow_cards: 0,
            yellow_red_cards: 0,
            red_cards: 0,
          },
          {
            id: "sr:player:21764",
            name: "Fellaini, Marouane",
            substituted_in: 1,
            substituted_out: 0,
            goals_scored: 0,
            assists: 0,
            own_goals: 0,
            yellow_cards: 0,
            yellow_red_cards: 0,
            red_cards: 0,
          },
        ],
      },
      {
        id: "sr:competitor:31",
        name: "Leicester City",
        abbreviation: "LEI",
        qualifier: "away",
        statistics: {
          ball_possession: 54,
          free_kicks: 15,
          throw_ins: 20,
          shots_on_target: 4,
          offsides: 2,
          fouls: 7,
          goal_kicks: 4,
          shots_blocked: 6,
          corner_kicks: 5,
          shots_saved: 4,
          shots_off_target: 4,
          yellow_cards: 1,
        },
        players: [
          {
            id: "sr:player:1076",
            name: "Schmeichel, Kasper",
            substituted_in: 0,
            substituted_out: 0,
            goals_scored: 0,
            assists: 0,
            own_goals: 0,
            yellow_cards: 0,
            yellow_red_cards: 0,
            red_cards: 0,
          },
          {
            id: "sr:player:308526",
            name: "Amartey, Daniel",
            substituted_in: 0,
            substituted_out: 1,
            goals_scored: 0,
            assists: 0,
            own_goals: 0,
            yellow_cards: 1,
            yellow_red_cards: 0,
            red_cards: 0,
          },
          {
            id: "sr:player:20375",
            name: "Morgan, Wes",
            substituted_in: 0,
            substituted_out: 0,
            goals_scored: 0,
            assists: 0,
            own_goals: 0,
            yellow_cards: 0,
            yellow_red_cards: 0,
            red_cards: 0,
          },
          {
            id: "sr:player:149380",
            name: "Maguire, Harry",
            substituted_in: 0,
            substituted_out: 0,
            goals_scored: 0,
            assists: 0,
            own_goals: 0,
            yellow_cards: 0,
            yellow_red_cards: 0,
            red_cards: 0,
          },
          {
            id: "sr:player:754594",
            name: "Chilwell, Benjamin",
            substituted_in: 0,
            substituted_out: 0,
            goals_scored: 0,
            assists: 0,
            own_goals: 0,
            yellow_cards: 0,
            yellow_red_cards: 0,
            red_cards: 0,
          },
          {
            id: "sr:player:221200",
            name: "Pereira, Ricardo",
            substituted_in: 0,
            substituted_out: 0,
            goals_scored: 0,
            assists: 0,
            own_goals: 0,
            yellow_cards: 0,
            yellow_red_cards: 0,
            red_cards: 0,
          },
          {
            id: "sr:player:795266",
            name: "Ndidi, Onyinye Wilfred",
            substituted_in: 0,
            substituted_out: 0,
            goals_scored: 0,
            assists: 0,
            own_goals: 0,
            yellow_cards: 0,
            yellow_red_cards: 0,
            red_cards: 0,
          },
          {
            id: "sr:player:30127",
            name: "Silva, Adrien",
            substituted_in: 0,
            substituted_out: 1,
            goals_scored: 0,
            assists: 0,
            own_goals: 0,
            yellow_cards: 0,
            yellow_red_cards: 0,
            red_cards: 0,
          },
          {
            id: "sr:player:356398",
            name: "Maddison, James",
            substituted_in: 0,
            substituted_out: 1,
            goals_scored: 0,
            assists: 0,
            own_goals: 0,
            yellow_cards: 0,
            yellow_red_cards: 0,
            red_cards: 0,
          },
          {
            id: "sr:player:355152",
            name: "Gray, Demarai",
            substituted_in: 0,
            substituted_out: 0,
            goals_scored: 0,
            assists: 0,
            own_goals: 0,
            yellow_cards: 0,
            yellow_red_cards: 0,
            red_cards: 0,
          },
          {
            id: "sr:player:359642",
            name: "Iheanacho, Kelechi",
            substituted_in: 0,
            substituted_out: 0,
            goals_scored: 0,
            assists: 0,
            own_goals: 0,
            yellow_cards: 0,
            yellow_red_cards: 0,
            red_cards: 0,
          },
          {
            id: "sr:player:123228",
            name: "Ghezzal, Rachid",
            substituted_in: 1,
            substituted_out: 0,
            goals_scored: 0,
            assists: 0,
            own_goals: 0,
            yellow_cards: 0,
            yellow_red_cards: 0,
            red_cards: 0,
          },
          {
            id: "sr:player:173827",
            name: "Vardy, Jamie",
            substituted_in: 1,
            substituted_out: 0,
            goals_scored: 1,
            assists: 0,
            own_goals: 0,
            yellow_cards: 0,
            yellow_red_cards: 0,
            red_cards: 0,
          },
          {
            id: "sr:player:32690",
            name: "Iborra, Vicente",
            substituted_in: 1,
            substituted_out: 0,
            goals_scored: 0,
            assists: 0,
            own_goals: 0,
            yellow_cards: 0,
            yellow_red_cards: 0,
            red_cards: 0,
          },
        ],
      },
    ],
  },
};
