/* tslint:disable: object-literal-key-quotes object-literal-sort-keys*/
export const scheduleByTournamentId = {
  generated_at: "2019-07-21T13:54:08+00:00",
  schema:
    "http://schemas.sportradar.com/bsa/soccer/v1/json/endpoints/soccer/tournament_schedule.json",
  tournament: {
    id: "sr:tournament:17",
    name: "Premier League",
    sport: {
      id: "sr:sport:1",
      name: "Soccer",
    },
    category: {
      id: "sr:category:1",
      name: "England",
      country_code: "ENG",
    },
  },
  sport_events: [
    {
      id: "sr:match:18427904",
      scheduled: "2019-12-28T15:00:00+00:00",
      start_time_tbd: true,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 20,
        phase: "regular season",
      },
      season: {
        id: "sr:season:66441",
        name: "Premier League 19/20",
        start_date: "2019-08-09",
        end_date: "2020-05-18",
        year: "19/20",
        tournament_id: "sr:tournament:17",
      },
      tournament: {
        id: "sr:tournament:17",
        name: "Premier League",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:1",
          name: "England",
          country_code: "ENG",
        },
      },
      competitors: [
        {
          id: "sr:competitor:42",
          name: "Arsenal FC",
          country: "England",
          country_code: "ENG",
          abbreviation: "ARS",
          qualifier: "home",
        },
        {
          id: "sr:competitor:38",
          name: "Chelsea FC",
          country: "England",
          country_code: "ENG",
          abbreviation: "CFC",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:624",
        name: "Emirates Stadium",
        capacity: 60272,
        city_name: "London",
        country_name: "England",
        map_coordinates: "51.555050,-0.108046",
        country_code: "ENG",
      },
    },
    {
      id: "sr:match:18427906",
      scheduled: "2019-12-28T15:00:00+00:00",
      start_time_tbd: true,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 20,
        phase: "regular season",
      },
      season: {
        id: "sr:season:66441",
        name: "Premier League 19/20",
        start_date: "2019-08-09",
        end_date: "2020-05-18",
        year: "19/20",
        tournament_id: "sr:tournament:17",
      },
      tournament: {
        id: "sr:tournament:17",
        name: "Premier League",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:1",
          name: "England",
          country_code: "ENG",
        },
      },
      competitors: [
        {
          id: "sr:competitor:30",
          name: "Brighton & Hove Albion",
          country: "England",
          country_code: "ENG",
          abbreviation: "BHA",
          qualifier: "home",
        },
        {
          id: "sr:competitor:60",
          name: "AFC Bournemouth",
          country: "England",
          country_code: "ENG",
          abbreviation: "BRN",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:2443",
        name: "American Express Community Stadium",
        capacity: 30750,
        city_name: "Falmer",
        country_name: "England",
        map_coordinates: "50.861822,-0.083278",
        country_code: "ENG",
      },
    },
    {
      id: "sr:match:18427908",
      scheduled: "2019-12-28T15:00:00+00:00",
      start_time_tbd: true,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 20,
        phase: "regular season",
      },
      season: {
        id: "sr:season:66441",
        name: "Premier League 19/20",
        start_date: "2019-08-09",
        end_date: "2020-05-18",
        year: "19/20",
        tournament_id: "sr:tournament:17",
      },
      tournament: {
        id: "sr:tournament:17",
        name: "Premier League",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:1",
          name: "England",
          country_code: "ENG",
        },
      },
      competitors: [
        {
          id: "sr:competitor:6",
          name: "Burnley FC",
          country: "England",
          country_code: "ENG",
          abbreviation: "BUR",
          qualifier: "home",
        },
        {
          id: "sr:competitor:35",
          name: "Manchester United",
          country: "England",
          country_code: "ENG",
          abbreviation: "MNU",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:806",
        name: "Turf Moor",
        capacity: 21401,
        city_name: "Burnley",
        country_name: "England",
        map_coordinates: "53.789167,-2.230278",
        country_code: "ENG",
      },
    },
    {
      id: "sr:match:18427910",
      scheduled: "2019-12-28T15:00:00+00:00",
      start_time_tbd: true,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 20,
        phase: "regular season",
      },
      season: {
        id: "sr:season:66441",
        name: "Premier League 19/20",
        start_date: "2019-08-09",
        end_date: "2020-05-18",
        year: "19/20",
        tournament_id: "sr:tournament:17",
      },
      tournament: {
        id: "sr:tournament:17",
        name: "Premier League",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:1",
          name: "England",
          country_code: "ENG",
        },
      },
      competitors: [
        {
          id: "sr:competitor:44",
          name: "Liverpool FC",
          country: "England",
          country_code: "ENG",
          abbreviation: "LFC",
          qualifier: "home",
        },
        {
          id: "sr:competitor:3",
          name: "Wolverhampton Wanderers",
          country: "England",
          country_code: "ENG",
          abbreviation: "WOL",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:579",
        name: "Anfield",
        capacity: 54074,
        city_name: "Liverpool",
        country_name: "England",
        map_coordinates: "53.430622,-2.960919",
        country_code: "ENG",
      },
    },
    {
      id: "sr:match:18427912",
      scheduled: "2019-12-28T15:00:00+00:00",
      start_time_tbd: true,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 20,
        phase: "regular season",
      },
      season: {
        id: "sr:season:66441",
        name: "Premier League 19/20",
        start_date: "2019-08-09",
        end_date: "2020-05-18",
        year: "19/20",
        tournament_id: "sr:tournament:17",
      },
      tournament: {
        id: "sr:tournament:17",
        name: "Premier League",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:1",
          name: "England",
          country_code: "ENG",
        },
      },
      competitors: [
        {
          id: "sr:competitor:17",
          name: "Manchester City",
          country: "England",
          country_code: "ENG",
          abbreviation: "MNC",
          qualifier: "home",
        },
        {
          id: "sr:competitor:15",
          name: "Sheffield United",
          country: "England",
          country_code: "ENG",
          abbreviation: "SHU",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:606",
        name: "Etihad Stadium",
        capacity: 46708,
        city_name: "Manchester",
        country_name: "England",
        map_coordinates: "53.484592,-2.202695",
        country_code: "ENG",
      },
    },
    {
      id: "sr:match:18427914",
      scheduled: "2019-12-28T15:00:00+00:00",
      start_time_tbd: true,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 20,
        phase: "regular season",
      },
      season: {
        id: "sr:season:66441",
        name: "Premier League 19/20",
        start_date: "2019-08-09",
        end_date: "2020-05-18",
        year: "19/20",
        tournament_id: "sr:tournament:17",
      },
      tournament: {
        id: "sr:tournament:17",
        name: "Premier League",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:1",
          name: "England",
          country_code: "ENG",
        },
      },
      competitors: [
        {
          id: "sr:competitor:39",
          name: "Newcastle United",
          country: "England",
          country_code: "ENG",
          abbreviation: "NEW",
          qualifier: "home",
        },
        {
          id: "sr:competitor:48",
          name: "Everton FC",
          country: "England",
          country_code: "ENG",
          abbreviation: "EVE",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:765",
        name: "St James' Park",
        capacity: 52338,
        city_name: "Newcastle upon Tyne",
        country_name: "England",
        map_coordinates: "54.975033,-1.615061",
        country_code: "ENG",
      },
    },
    {
      id: "sr:match:18427916",
      scheduled: "2019-12-28T15:00:00+00:00",
      start_time_tbd: true,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 20,
        phase: "regular season",
      },
      season: {
        id: "sr:season:66441",
        name: "Premier League 19/20",
        start_date: "2019-08-09",
        end_date: "2020-05-18",
        year: "19/20",
        tournament_id: "sr:tournament:17",
      },
      tournament: {
        id: "sr:tournament:17",
        name: "Premier League",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:1",
          name: "England",
          country_code: "ENG",
        },
      },
      competitors: [
        {
          id: "sr:competitor:263",
          name: "Norwich City",
          country: "England",
          country_code: "ENG",
          abbreviation: "NOR",
          qualifier: "home",
        },
        {
          id: "sr:competitor:33",
          name: "Tottenham Hotspur",
          country: "England",
          country_code: "ENG",
          abbreviation: "TOT",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:2221",
        name: "Carrow Road",
        capacity: 27244,
        city_name: "Norwich",
        country_name: "England",
        map_coordinates: "52.621647,1.309642",
        country_code: "ENG",
      },
    },
    {
      id: "sr:match:18427918",
      scheduled: "2019-12-28T15:00:00+00:00",
      start_time_tbd: true,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 20,
        phase: "regular season",
      },
      season: {
        id: "sr:season:66441",
        name: "Premier League 19/20",
        start_date: "2019-08-09",
        end_date: "2020-05-18",
        year: "19/20",
        tournament_id: "sr:tournament:17",
      },
      tournament: {
        id: "sr:tournament:17",
        name: "Premier League",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:1",
          name: "England",
          country_code: "ENG",
        },
      },
      competitors: [
        {
          id: "sr:competitor:45",
          name: "Southampton FC",
          country: "England",
          country_code: "ENG",
          abbreviation: "SOT",
          qualifier: "home",
        },
        {
          id: "sr:competitor:7",
          name: "Crystal Palace",
          country: "England",
          country_code: "ENG",
          abbreviation: "PAL",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:2231",
        name: "St. Mary's Stadium",
        capacity: 32505,
        city_name: "Southampton",
        country_name: "England",
        map_coordinates: "50.905833,-1.391111",
        country_code: "ENG",
      },
    },
    {
      id: "sr:match:18427920",
      scheduled: "2019-12-28T15:00:00+00:00",
      start_time_tbd: true,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 20,
        phase: "regular season",
      },
      season: {
        id: "sr:season:66441",
        name: "Premier League 19/20",
        start_date: "2019-08-09",
        end_date: "2020-05-18",
        year: "19/20",
        tournament_id: "sr:tournament:17",
      },
      tournament: {
        id: "sr:tournament:17",
        name: "Premier League",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:1",
          name: "England",
          country_code: "ENG",
        },
      },
      competitors: [
        {
          id: "sr:competitor:24",
          name: "Watford FC",
          country: "England",
          country_code: "ENG",
          abbreviation: "WAT",
          qualifier: "home",
        },
        {
          id: "sr:competitor:40",
          name: "Aston Villa",
          country: "England",
          country_code: "ENG",
          abbreviation: "VIL",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:813",
        name: "Vicarage Road",
        capacity: 21400,
        city_name: "Watford",
        country_name: "England",
        map_coordinates: "51.649836,-0.401486",
        country_code: "ENG",
      },
    },
    {
      id: "sr:match:18427922",
      scheduled: "2019-12-28T15:00:00+00:00",
      start_time_tbd: true,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 20,
        phase: "regular season",
      },
      season: {
        id: "sr:season:66441",
        name: "Premier League 19/20",
        start_date: "2019-08-09",
        end_date: "2020-05-18",
        year: "19/20",
        tournament_id: "sr:tournament:17",
      },
      tournament: {
        id: "sr:tournament:17",
        name: "Premier League",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:1",
          name: "England",
          country_code: "ENG",
        },
      },
      competitors: [
        {
          id: "sr:competitor:37",
          name: "West Ham United",
          country: "England",
          country_code: "ENG",
          abbreviation: "WHU",
          qualifier: "home",
        },
        {
          id: "sr:competitor:31",
          name: "Leicester City",
          country: "England",
          country_code: "ENG",
          abbreviation: "LEI",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:18379",
        name: "London Stadium",
        capacity: 66000,
        city_name: "London",
        country_name: "England",
        map_coordinates: "null,null",
        country_code: "ENG",
      },
    },
    {
      id: "sr:match:18427924",
      scheduled: "2020-01-01T15:00:00+00:00",
      start_time_tbd: true,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 21,
        phase: "regular season",
      },
      season: {
        id: "sr:season:66441",
        name: "Premier League 19/20",
        start_date: "2019-08-09",
        end_date: "2020-05-18",
        year: "19/20",
        tournament_id: "sr:tournament:17",
      },
      tournament: {
        id: "sr:tournament:17",
        name: "Premier League",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:1",
          name: "England",
          country_code: "ENG",
        },
      },
      competitors: [
        {
          id: "sr:competitor:42",
          name: "Arsenal FC",
          country: "England",
          country_code: "ENG",
          abbreviation: "ARS",
          qualifier: "home",
        },
        {
          id: "sr:competitor:35",
          name: "Manchester United",
          country: "England",
          country_code: "ENG",
          abbreviation: "MNU",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:624",
        name: "Emirates Stadium",
        capacity: 60272,
        city_name: "London",
        country_name: "England",
        map_coordinates: "51.555050,-0.108046",
        country_code: "ENG",
      },
    },
    {
      id: "sr:match:18427926",
      scheduled: "2020-01-01T15:00:00+00:00",
      start_time_tbd: true,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 21,
        phase: "regular season",
      },
      season: {
        id: "sr:season:66441",
        name: "Premier League 19/20",
        start_date: "2019-08-09",
        end_date: "2020-05-18",
        year: "19/20",
        tournament_id: "sr:tournament:17",
      },
      tournament: {
        id: "sr:tournament:17",
        name: "Premier League",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:1",
          name: "England",
          country_code: "ENG",
        },
      },
      competitors: [
        {
          id: "sr:competitor:30",
          name: "Brighton & Hove Albion",
          country: "England",
          country_code: "ENG",
          abbreviation: "BHA",
          qualifier: "home",
        },
        {
          id: "sr:competitor:38",
          name: "Chelsea FC",
          country: "England",
          country_code: "ENG",
          abbreviation: "CFC",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:2443",
        name: "American Express Community Stadium",
        capacity: 30750,
        city_name: "Falmer",
        country_name: "England",
        map_coordinates: "50.861822,-0.083278",
        country_code: "ENG",
      },
    },
    {
      id: "sr:match:18427928",
      scheduled: "2020-01-01T15:00:00+00:00",
      start_time_tbd: true,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 21,
        phase: "regular season",
      },
      season: {
        id: "sr:season:66441",
        name: "Premier League 19/20",
        start_date: "2019-08-09",
        end_date: "2020-05-18",
        year: "19/20",
        tournament_id: "sr:tournament:17",
      },
      tournament: {
        id: "sr:tournament:17",
        name: "Premier League",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:1",
          name: "England",
          country_code: "ENG",
        },
      },
      competitors: [
        {
          id: "sr:competitor:6",
          name: "Burnley FC",
          country: "England",
          country_code: "ENG",
          abbreviation: "BUR",
          qualifier: "home",
        },
        {
          id: "sr:competitor:40",
          name: "Aston Villa",
          country: "England",
          country_code: "ENG",
          abbreviation: "VIL",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:806",
        name: "Turf Moor",
        capacity: 21401,
        city_name: "Burnley",
        country_name: "England",
        map_coordinates: "53.789167,-2.230278",
        country_code: "ENG",
      },
    },
    {
      id: "sr:match:18427930",
      scheduled: "2020-01-01T15:00:00+00:00",
      start_time_tbd: true,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 21,
        phase: "regular season",
      },
      season: {
        id: "sr:season:66441",
        name: "Premier League 19/20",
        start_date: "2019-08-09",
        end_date: "2020-05-18",
        year: "19/20",
        tournament_id: "sr:tournament:17",
      },
      tournament: {
        id: "sr:tournament:17",
        name: "Premier League",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:1",
          name: "England",
          country_code: "ENG",
        },
      },
      competitors: [
        {
          id: "sr:competitor:44",
          name: "Liverpool FC",
          country: "England",
          country_code: "ENG",
          abbreviation: "LFC",
          qualifier: "home",
        },
        {
          id: "sr:competitor:15",
          name: "Sheffield United",
          country: "England",
          country_code: "ENG",
          abbreviation: "SHU",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:579",
        name: "Anfield",
        capacity: 54074,
        city_name: "Liverpool",
        country_name: "England",
        map_coordinates: "53.430622,-2.960919",
        country_code: "ENG",
      },
    },
    {
      id: "sr:match:18427932",
      scheduled: "2020-01-01T15:00:00+00:00",
      start_time_tbd: true,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 21,
        phase: "regular season",
      },
      season: {
        id: "sr:season:66441",
        name: "Premier League 19/20",
        start_date: "2019-08-09",
        end_date: "2020-05-18",
        year: "19/20",
        tournament_id: "sr:tournament:17",
      },
      tournament: {
        id: "sr:tournament:17",
        name: "Premier League",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:1",
          name: "England",
          country_code: "ENG",
        },
      },
      competitors: [
        {
          id: "sr:competitor:17",
          name: "Manchester City",
          country: "England",
          country_code: "ENG",
          abbreviation: "MNC",
          qualifier: "home",
        },
        {
          id: "sr:competitor:48",
          name: "Everton FC",
          country: "England",
          country_code: "ENG",
          abbreviation: "EVE",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:606",
        name: "Etihad Stadium",
        capacity: 46708,
        city_name: "Manchester",
        country_name: "England",
        map_coordinates: "53.484592,-2.202695",
        country_code: "ENG",
      },
    },
    {
      id: "sr:match:18427934",
      scheduled: "2020-01-01T15:00:00+00:00",
      start_time_tbd: true,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 21,
        phase: "regular season",
      },
      season: {
        id: "sr:season:66441",
        name: "Premier League 19/20",
        start_date: "2019-08-09",
        end_date: "2020-05-18",
        year: "19/20",
        tournament_id: "sr:tournament:17",
      },
      tournament: {
        id: "sr:tournament:17",
        name: "Premier League",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:1",
          name: "England",
          country_code: "ENG",
        },
      },
      competitors: [
        {
          id: "sr:competitor:39",
          name: "Newcastle United",
          country: "England",
          country_code: "ENG",
          abbreviation: "NEW",
          qualifier: "home",
        },
        {
          id: "sr:competitor:31",
          name: "Leicester City",
          country: "England",
          country_code: "ENG",
          abbreviation: "LEI",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:765",
        name: "St James' Park",
        capacity: 52338,
        city_name: "Newcastle upon Tyne",
        country_name: "England",
        map_coordinates: "54.975033,-1.615061",
        country_code: "ENG",
      },
    },
    {
      id: "sr:match:18427936",
      scheduled: "2020-01-01T15:00:00+00:00",
      start_time_tbd: true,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 21,
        phase: "regular season",
      },
      season: {
        id: "sr:season:66441",
        name: "Premier League 19/20",
        start_date: "2019-08-09",
        end_date: "2020-05-18",
        year: "19/20",
        tournament_id: "sr:tournament:17",
      },
      tournament: {
        id: "sr:tournament:17",
        name: "Premier League",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:1",
          name: "England",
          country_code: "ENG",
        },
      },
      competitors: [
        {
          id: "sr:competitor:263",
          name: "Norwich City",
          country: "England",
          country_code: "ENG",
          abbreviation: "NOR",
          qualifier: "home",
        },
        {
          id: "sr:competitor:7",
          name: "Crystal Palace",
          country: "England",
          country_code: "ENG",
          abbreviation: "PAL",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:2221",
        name: "Carrow Road",
        capacity: 27244,
        city_name: "Norwich",
        country_name: "England",
        map_coordinates: "52.621647,1.309642",
        country_code: "ENG",
      },
    },
    {
      id: "sr:match:18427938",
      scheduled: "2020-01-01T15:00:00+00:00",
      start_time_tbd: true,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 21,
        phase: "regular season",
      },
      season: {
        id: "sr:season:66441",
        name: "Premier League 19/20",
        start_date: "2019-08-09",
        end_date: "2020-05-18",
        year: "19/20",
        tournament_id: "sr:tournament:17",
      },
      tournament: {
        id: "sr:tournament:17",
        name: "Premier League",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:1",
          name: "England",
          country_code: "ENG",
        },
      },
      competitors: [
        {
          id: "sr:competitor:45",
          name: "Southampton FC",
          country: "England",
          country_code: "ENG",
          abbreviation: "SOT",
          qualifier: "home",
        },
        {
          id: "sr:competitor:33",
          name: "Tottenham Hotspur",
          country: "England",
          country_code: "ENG",
          abbreviation: "TOT",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:2231",
        name: "St. Mary's Stadium",
        capacity: 32505,
        city_name: "Southampton",
        country_name: "England",
        map_coordinates: "50.905833,-1.391111",
        country_code: "ENG",
      },
    },
    {
      id: "sr:match:18427940",
      scheduled: "2020-01-01T15:00:00+00:00",
      start_time_tbd: true,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 21,
        phase: "regular season",
      },
      season: {
        id: "sr:season:66441",
        name: "Premier League 19/20",
        start_date: "2019-08-09",
        end_date: "2020-05-18",
        year: "19/20",
        tournament_id: "sr:tournament:17",
      },
      tournament: {
        id: "sr:tournament:17",
        name: "Premier League",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:1",
          name: "England",
          country_code: "ENG",
        },
      },
      competitors: [
        {
          id: "sr:competitor:24",
          name: "Watford FC",
          country: "England",
          country_code: "ENG",
          abbreviation: "WAT",
          qualifier: "home",
        },
        {
          id: "sr:competitor:3",
          name: "Wolverhampton Wanderers",
          country: "England",
          country_code: "ENG",
          abbreviation: "WOL",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:813",
        name: "Vicarage Road",
        capacity: 21400,
        city_name: "Watford",
        country_name: "England",
        map_coordinates: "51.649836,-0.401486",
        country_code: "ENG",
      },
    },
    {
      id: "sr:match:18427942",
      scheduled: "2020-01-01T15:00:00+00:00",
      start_time_tbd: true,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 21,
        phase: "regular season",
      },
      season: {
        id: "sr:season:66441",
        name: "Premier League 19/20",
        start_date: "2019-08-09",
        end_date: "2020-05-18",
        year: "19/20",
        tournament_id: "sr:tournament:17",
      },
      tournament: {
        id: "sr:tournament:17",
        name: "Premier League",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:1",
          name: "England",
          country_code: "ENG",
        },
      },
      competitors: [
        {
          id: "sr:competitor:37",
          name: "West Ham United",
          country: "England",
          country_code: "ENG",
          abbreviation: "WHU",
          qualifier: "home",
        },
        {
          id: "sr:competitor:60",
          name: "AFC Bournemouth",
          country: "England",
          country_code: "ENG",
          abbreviation: "BRN",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:18379",
        name: "London Stadium",
        capacity: 66000,
        city_name: "London",
        country_name: "England",
        map_coordinates: "null,null",
        country_code: "ENG",
      },
    },
    {
      id: "sr:match:18427944",
      scheduled: "2020-01-11T15:00:00+00:00",
      start_time_tbd: true,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 22,
        phase: "regular season",
      },
      season: {
        id: "sr:season:66441",
        name: "Premier League 19/20",
        start_date: "2019-08-09",
        end_date: "2020-05-18",
        year: "19/20",
        tournament_id: "sr:tournament:17",
      },
      tournament: {
        id: "sr:tournament:17",
        name: "Premier League",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:1",
          name: "England",
          country_code: "ENG",
        },
      },
      competitors: [
        {
          id: "sr:competitor:40",
          name: "Aston Villa",
          country: "England",
          country_code: "ENG",
          abbreviation: "VIL",
          qualifier: "home",
        },
        {
          id: "sr:competitor:17",
          name: "Manchester City",
          country: "England",
          country_code: "ENG",
          abbreviation: "MNC",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:815",
        name: "Villa Park",
        capacity: 42682,
        city_name: "Birmingham",
        country_name: "England",
        map_coordinates: "52.509212,-1.885288",
        country_code: "ENG",
      },
    },
    {
      id: "sr:match:18427946",
      scheduled: "2020-01-11T15:00:00+00:00",
      start_time_tbd: true,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 22,
        phase: "regular season",
      },
      season: {
        id: "sr:season:66441",
        name: "Premier League 19/20",
        start_date: "2019-08-09",
        end_date: "2020-05-18",
        year: "19/20",
        tournament_id: "sr:tournament:17",
      },
      tournament: {
        id: "sr:tournament:17",
        name: "Premier League",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:1",
          name: "England",
          country_code: "ENG",
        },
      },
      competitors: [
        {
          id: "sr:competitor:60",
          name: "AFC Bournemouth",
          country: "England",
          country_code: "ENG",
          abbreviation: "BRN",
          qualifier: "home",
        },
        {
          id: "sr:competitor:24",
          name: "Watford FC",
          country: "England",
          country_code: "ENG",
          abbreviation: "WAT",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:2990",
        name: "Vitality Stadium",
        capacity: 11700,
        city_name: "Bournemouth",
        country_name: "England",
        map_coordinates: "50.735278,-1.838333",
        country_code: "ENG",
      },
    },
    {
      id: "sr:match:18427948",
      scheduled: "2020-01-11T15:00:00+00:00",
      start_time_tbd: true,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 22,
        phase: "regular season",
      },
      season: {
        id: "sr:season:66441",
        name: "Premier League 19/20",
        start_date: "2019-08-09",
        end_date: "2020-05-18",
        year: "19/20",
        tournament_id: "sr:tournament:17",
      },
      tournament: {
        id: "sr:tournament:17",
        name: "Premier League",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:1",
          name: "England",
          country_code: "ENG",
        },
      },
      competitors: [
        {
          id: "sr:competitor:38",
          name: "Chelsea FC",
          country: "England",
          country_code: "ENG",
          abbreviation: "CFC",
          qualifier: "home",
        },
        {
          id: "sr:competitor:6",
          name: "Burnley FC",
          country: "England",
          country_code: "ENG",
          abbreviation: "BUR",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:799",
        name: "Stamford Bridge",
        capacity: 41798,
        city_name: "London",
        country_name: "England",
        map_coordinates: "51.481579,-0.191094",
        country_code: "ENG",
      },
    },
    {
      id: "sr:match:18427950",
      scheduled: "2020-01-11T15:00:00+00:00",
      start_time_tbd: true,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 22,
        phase: "regular season",
      },
      season: {
        id: "sr:season:66441",
        name: "Premier League 19/20",
        start_date: "2019-08-09",
        end_date: "2020-05-18",
        year: "19/20",
        tournament_id: "sr:tournament:17",
      },
      tournament: {
        id: "sr:tournament:17",
        name: "Premier League",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:1",
          name: "England",
          country_code: "ENG",
        },
      },
      competitors: [
        {
          id: "sr:competitor:7",
          name: "Crystal Palace",
          country: "England",
          country_code: "ENG",
          abbreviation: "PAL",
          qualifier: "home",
        },
        {
          id: "sr:competitor:42",
          name: "Arsenal FC",
          country: "England",
          country_code: "ENG",
          abbreviation: "ARS",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:10",
        name: "Selhurst Park",
        capacity: 25073,
        city_name: "London",
        country_name: "England",
        map_coordinates: "51.398333,-0.085556",
        country_code: "ENG",
      },
    },
    {
      id: "sr:match:18427952",
      scheduled: "2020-01-11T15:00:00+00:00",
      start_time_tbd: true,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 22,
        phase: "regular season",
      },
      season: {
        id: "sr:season:66441",
        name: "Premier League 19/20",
        start_date: "2019-08-09",
        end_date: "2020-05-18",
        year: "19/20",
        tournament_id: "sr:tournament:17",
      },
      tournament: {
        id: "sr:tournament:17",
        name: "Premier League",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:1",
          name: "England",
          country_code: "ENG",
        },
      },
      competitors: [
        {
          id: "sr:competitor:48",
          name: "Everton FC",
          country: "England",
          country_code: "ENG",
          abbreviation: "EVE",
          qualifier: "home",
        },
        {
          id: "sr:competitor:30",
          name: "Brighton & Hove Albion",
          country: "England",
          country_code: "ENG",
          abbreviation: "BHA",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:12",
        name: "Goodison Park",
        capacity: 39571,
        city_name: "Liverpool",
        country_name: "England",
        map_coordinates: "53.439255,-2.967065",
        country_code: "ENG",
      },
    },
    {
      id: "sr:match:18427954",
      scheduled: "2020-01-11T15:00:00+00:00",
      start_time_tbd: true,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 22,
        phase: "regular season",
      },
      season: {
        id: "sr:season:66441",
        name: "Premier League 19/20",
        start_date: "2019-08-09",
        end_date: "2020-05-18",
        year: "19/20",
        tournament_id: "sr:tournament:17",
      },
      tournament: {
        id: "sr:tournament:17",
        name: "Premier League",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:1",
          name: "England",
          country_code: "ENG",
        },
      },
      competitors: [
        {
          id: "sr:competitor:31",
          name: "Leicester City",
          country: "England",
          country_code: "ENG",
          abbreviation: "LEI",
          qualifier: "home",
        },
        {
          id: "sr:competitor:45",
          name: "Southampton FC",
          country: "England",
          country_code: "ENG",
          abbreviation: "SOT",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:2183",
        name: "King Power Stadium",
        capacity: 32312,
        city_name: "Leicester",
        country_name: "England",
        map_coordinates: "52.620278,-1.142222",
        country_code: "ENG",
      },
    },
    {
      id: "sr:match:18427956",
      scheduled: "2020-01-11T15:00:00+00:00",
      start_time_tbd: true,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 22,
        phase: "regular season",
      },
      season: {
        id: "sr:season:66441",
        name: "Premier League 19/20",
        start_date: "2019-08-09",
        end_date: "2020-05-18",
        year: "19/20",
        tournament_id: "sr:tournament:17",
      },
      tournament: {
        id: "sr:tournament:17",
        name: "Premier League",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:1",
          name: "England",
          country_code: "ENG",
        },
      },
      competitors: [
        {
          id: "sr:competitor:35",
          name: "Manchester United",
          country: "England",
          country_code: "ENG",
          abbreviation: "MNU",
          qualifier: "home",
        },
        {
          id: "sr:competitor:263",
          name: "Norwich City",
          country: "England",
          country_code: "ENG",
          abbreviation: "NOR",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:9",
        name: "Old Trafford",
        capacity: 75635,
        city_name: "Manchester",
        country_name: "England",
        map_coordinates: "53.463150,-2.291444",
        country_code: "ENG",
      },
    },
    {
      id: "sr:match:18427958",
      scheduled: "2020-01-11T15:00:00+00:00",
      start_time_tbd: true,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 22,
        phase: "regular season",
      },
      season: {
        id: "sr:season:66441",
        name: "Premier League 19/20",
        start_date: "2019-08-09",
        end_date: "2020-05-18",
        year: "19/20",
        tournament_id: "sr:tournament:17",
      },
      tournament: {
        id: "sr:tournament:17",
        name: "Premier League",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:1",
          name: "England",
          country_code: "ENG",
        },
      },
      competitors: [
        {
          id: "sr:competitor:15",
          name: "Sheffield United",
          country: "England",
          country_code: "ENG",
          abbreviation: "SHU",
          qualifier: "home",
        },
        {
          id: "sr:competitor:37",
          name: "West Ham United",
          country: "England",
          country_code: "ENG",
          abbreviation: "WHU",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:598",
        name: "Bramall Lane",
        capacity: 32702,
        city_name: "Sheffield",
        country_name: "England",
        map_coordinates: "53.370278,-1.470833",
        country_code: "ENG",
      },
    },
    {
      id: "sr:match:18427960",
      scheduled: "2020-01-11T15:00:00+00:00",
      start_time_tbd: true,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 22,
        phase: "regular season",
      },
      season: {
        id: "sr:season:66441",
        name: "Premier League 19/20",
        start_date: "2019-08-09",
        end_date: "2020-05-18",
        year: "19/20",
        tournament_id: "sr:tournament:17",
      },
      tournament: {
        id: "sr:tournament:17",
        name: "Premier League",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:1",
          name: "England",
          country_code: "ENG",
        },
      },
      competitors: [
        {
          id: "sr:competitor:33",
          name: "Tottenham Hotspur",
          country: "England",
          country_code: "ENG",
          abbreviation: "TOT",
          qualifier: "home",
        },
        {
          id: "sr:competitor:44",
          name: "Liverpool FC",
          country: "England",
          country_code: "ENG",
          abbreviation: "LFC",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:28762",
        name: "Tottenham Hotspur Stadium",
        capacity: 62000,
        city_name: "London",
        country_name: "England",
        map_coordinates: "51.604444, -0.066389",
        country_code: "ENG",
      },
    },
    {
      id: "sr:match:18427962",
      scheduled: "2020-01-11T15:00:00+00:00",
      start_time_tbd: true,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 22,
        phase: "regular season",
      },
      season: {
        id: "sr:season:66441",
        name: "Premier League 19/20",
        start_date: "2019-08-09",
        end_date: "2020-05-18",
        year: "19/20",
        tournament_id: "sr:tournament:17",
      },
      tournament: {
        id: "sr:tournament:17",
        name: "Premier League",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:1",
          name: "England",
          country_code: "ENG",
        },
      },
      competitors: [
        {
          id: "sr:competitor:3",
          name: "Wolverhampton Wanderers",
          country: "England",
          country_code: "ENG",
          abbreviation: "WOL",
          qualifier: "home",
        },
        {
          id: "sr:competitor:39",
          name: "Newcastle United",
          country: "England",
          country_code: "ENG",
          abbreviation: "NEW",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:1272",
        name: "Molineux Stadium",
        capacity: 30852,
        city_name: "Wolverhampton",
        country_name: "England",
        map_coordinates: "52.590195,-2.131226",
        country_code: "ENG",
      },
    },
    {
      id: "sr:match:18427964",
      scheduled: "2020-01-18T15:00:00+00:00",
      start_time_tbd: true,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 23,
        phase: "regular season",
      },
      season: {
        id: "sr:season:66441",
        name: "Premier League 19/20",
        start_date: "2019-08-09",
        end_date: "2020-05-18",
        year: "19/20",
        tournament_id: "sr:tournament:17",
      },
      tournament: {
        id: "sr:tournament:17",
        name: "Premier League",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:1",
          name: "England",
          country_code: "ENG",
        },
      },
      competitors: [
        {
          id: "sr:competitor:42",
          name: "Arsenal FC",
          country: "England",
          country_code: "ENG",
          abbreviation: "ARS",
          qualifier: "home",
        },
        {
          id: "sr:competitor:15",
          name: "Sheffield United",
          country: "England",
          country_code: "ENG",
          abbreviation: "SHU",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:624",
        name: "Emirates Stadium",
        capacity: 60272,
        city_name: "London",
        country_name: "England",
        map_coordinates: "51.555050,-0.108046",
        country_code: "ENG",
      },
    },
    {
      id: "sr:match:18427966",
      scheduled: "2020-01-18T15:00:00+00:00",
      start_time_tbd: true,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 23,
        phase: "regular season",
      },
      season: {
        id: "sr:season:66441",
        name: "Premier League 19/20",
        start_date: "2019-08-09",
        end_date: "2020-05-18",
        year: "19/20",
        tournament_id: "sr:tournament:17",
      },
      tournament: {
        id: "sr:tournament:17",
        name: "Premier League",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:1",
          name: "England",
          country_code: "ENG",
        },
      },
      competitors: [
        {
          id: "sr:competitor:30",
          name: "Brighton & Hove Albion",
          country: "England",
          country_code: "ENG",
          abbreviation: "BHA",
          qualifier: "home",
        },
        {
          id: "sr:competitor:40",
          name: "Aston Villa",
          country: "England",
          country_code: "ENG",
          abbreviation: "VIL",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:2443",
        name: "American Express Community Stadium",
        capacity: 30750,
        city_name: "Falmer",
        country_name: "England",
        map_coordinates: "50.861822,-0.083278",
        country_code: "ENG",
      },
    },
    {
      id: "sr:match:18427968",
      scheduled: "2020-01-18T15:00:00+00:00",
      start_time_tbd: true,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 23,
        phase: "regular season",
      },
      season: {
        id: "sr:season:66441",
        name: "Premier League 19/20",
        start_date: "2019-08-09",
        end_date: "2020-05-18",
        year: "19/20",
        tournament_id: "sr:tournament:17",
      },
      tournament: {
        id: "sr:tournament:17",
        name: "Premier League",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:1",
          name: "England",
          country_code: "ENG",
        },
      },
      competitors: [
        {
          id: "sr:competitor:6",
          name: "Burnley FC",
          country: "England",
          country_code: "ENG",
          abbreviation: "BUR",
          qualifier: "home",
        },
        {
          id: "sr:competitor:31",
          name: "Leicester City",
          country: "England",
          country_code: "ENG",
          abbreviation: "LEI",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:806",
        name: "Turf Moor",
        capacity: 21401,
        city_name: "Burnley",
        country_name: "England",
        map_coordinates: "53.789167,-2.230278",
        country_code: "ENG",
      },
    },
    {
      id: "sr:match:18427970",
      scheduled: "2020-01-18T15:00:00+00:00",
      start_time_tbd: true,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 23,
        phase: "regular season",
      },
      season: {
        id: "sr:season:66441",
        name: "Premier League 19/20",
        start_date: "2019-08-09",
        end_date: "2020-05-18",
        year: "19/20",
        tournament_id: "sr:tournament:17",
      },
      tournament: {
        id: "sr:tournament:17",
        name: "Premier League",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:1",
          name: "England",
          country_code: "ENG",
        },
      },
      competitors: [
        {
          id: "sr:competitor:44",
          name: "Liverpool FC",
          country: "England",
          country_code: "ENG",
          abbreviation: "LFC",
          qualifier: "home",
        },
        {
          id: "sr:competitor:35",
          name: "Manchester United",
          country: "England",
          country_code: "ENG",
          abbreviation: "MNU",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:579",
        name: "Anfield",
        capacity: 54074,
        city_name: "Liverpool",
        country_name: "England",
        map_coordinates: "53.430622,-2.960919",
        country_code: "ENG",
      },
    },
    {
      id: "sr:match:18427972",
      scheduled: "2020-01-18T15:00:00+00:00",
      start_time_tbd: true,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 23,
        phase: "regular season",
      },
      season: {
        id: "sr:season:66441",
        name: "Premier League 19/20",
        start_date: "2019-08-09",
        end_date: "2020-05-18",
        year: "19/20",
        tournament_id: "sr:tournament:17",
      },
      tournament: {
        id: "sr:tournament:17",
        name: "Premier League",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:1",
          name: "England",
          country_code: "ENG",
        },
      },
      competitors: [
        {
          id: "sr:competitor:17",
          name: "Manchester City",
          country: "England",
          country_code: "ENG",
          abbreviation: "MNC",
          qualifier: "home",
        },
        {
          id: "sr:competitor:7",
          name: "Crystal Palace",
          country: "England",
          country_code: "ENG",
          abbreviation: "PAL",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:606",
        name: "Etihad Stadium",
        capacity: 46708,
        city_name: "Manchester",
        country_name: "England",
        map_coordinates: "53.484592,-2.202695",
        country_code: "ENG",
      },
    },
    {
      id: "sr:match:18427974",
      scheduled: "2020-01-18T15:00:00+00:00",
      start_time_tbd: true,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 23,
        phase: "regular season",
      },
      season: {
        id: "sr:season:66441",
        name: "Premier League 19/20",
        start_date: "2019-08-09",
        end_date: "2020-05-18",
        year: "19/20",
        tournament_id: "sr:tournament:17",
      },
      tournament: {
        id: "sr:tournament:17",
        name: "Premier League",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:1",
          name: "England",
          country_code: "ENG",
        },
      },
      competitors: [
        {
          id: "sr:competitor:39",
          name: "Newcastle United",
          country: "England",
          country_code: "ENG",
          abbreviation: "NEW",
          qualifier: "home",
        },
        {
          id: "sr:competitor:38",
          name: "Chelsea FC",
          country: "England",
          country_code: "ENG",
          abbreviation: "CFC",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:765",
        name: "St James' Park",
        capacity: 52338,
        city_name: "Newcastle upon Tyne",
        country_name: "England",
        map_coordinates: "54.975033,-1.615061",
        country_code: "ENG",
      },
    },
    {
      id: "sr:match:18427976",
      scheduled: "2020-01-18T15:00:00+00:00",
      start_time_tbd: true,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 23,
        phase: "regular season",
      },
      season: {
        id: "sr:season:66441",
        name: "Premier League 19/20",
        start_date: "2019-08-09",
        end_date: "2020-05-18",
        year: "19/20",
        tournament_id: "sr:tournament:17",
      },
      tournament: {
        id: "sr:tournament:17",
        name: "Premier League",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:1",
          name: "England",
          country_code: "ENG",
        },
      },
      competitors: [
        {
          id: "sr:competitor:263",
          name: "Norwich City",
          country: "England",
          country_code: "ENG",
          abbreviation: "NOR",
          qualifier: "home",
        },
        {
          id: "sr:competitor:60",
          name: "AFC Bournemouth",
          country: "England",
          country_code: "ENG",
          abbreviation: "BRN",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:2221",
        name: "Carrow Road",
        capacity: 27244,
        city_name: "Norwich",
        country_name: "England",
        map_coordinates: "52.621647,1.309642",
        country_code: "ENG",
      },
    },
    {
      id: "sr:match:18427978",
      scheduled: "2020-01-18T15:00:00+00:00",
      start_time_tbd: true,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 23,
        phase: "regular season",
      },
      season: {
        id: "sr:season:66441",
        name: "Premier League 19/20",
        start_date: "2019-08-09",
        end_date: "2020-05-18",
        year: "19/20",
        tournament_id: "sr:tournament:17",
      },
      tournament: {
        id: "sr:tournament:17",
        name: "Premier League",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:1",
          name: "England",
          country_code: "ENG",
        },
      },
      competitors: [
        {
          id: "sr:competitor:45",
          name: "Southampton FC",
          country: "England",
          country_code: "ENG",
          abbreviation: "SOT",
          qualifier: "home",
        },
        {
          id: "sr:competitor:3",
          name: "Wolverhampton Wanderers",
          country: "England",
          country_code: "ENG",
          abbreviation: "WOL",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:2231",
        name: "St. Mary's Stadium",
        capacity: 32505,
        city_name: "Southampton",
        country_name: "England",
        map_coordinates: "50.905833,-1.391111",
        country_code: "ENG",
      },
    },
    {
      id: "sr:match:18427980",
      scheduled: "2020-01-18T15:00:00+00:00",
      start_time_tbd: true,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 23,
        phase: "regular season",
      },
      season: {
        id: "sr:season:66441",
        name: "Premier League 19/20",
        start_date: "2019-08-09",
        end_date: "2020-05-18",
        year: "19/20",
        tournament_id: "sr:tournament:17",
      },
      tournament: {
        id: "sr:tournament:17",
        name: "Premier League",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:1",
          name: "England",
          country_code: "ENG",
        },
      },
      competitors: [
        {
          id: "sr:competitor:24",
          name: "Watford FC",
          country: "England",
          country_code: "ENG",
          abbreviation: "WAT",
          qualifier: "home",
        },
        {
          id: "sr:competitor:33",
          name: "Tottenham Hotspur",
          country: "England",
          country_code: "ENG",
          abbreviation: "TOT",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:813",
        name: "Vicarage Road",
        capacity: 21400,
        city_name: "Watford",
        country_name: "England",
        map_coordinates: "51.649836,-0.401486",
        country_code: "ENG",
      },
    },
    {
      id: "sr:match:18427982",
      scheduled: "2020-01-18T15:00:00+00:00",
      start_time_tbd: true,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 23,
        phase: "regular season",
      },
      season: {
        id: "sr:season:66441",
        name: "Premier League 19/20",
        start_date: "2019-08-09",
        end_date: "2020-05-18",
        year: "19/20",
        tournament_id: "sr:tournament:17",
      },
      tournament: {
        id: "sr:tournament:17",
        name: "Premier League",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:1",
          name: "England",
          country_code: "ENG",
        },
      },
      competitors: [
        {
          id: "sr:competitor:37",
          name: "West Ham United",
          country: "England",
          country_code: "ENG",
          abbreviation: "WHU",
          qualifier: "home",
        },
        {
          id: "sr:competitor:48",
          name: "Everton FC",
          country: "England",
          country_code: "ENG",
          abbreviation: "EVE",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:18379",
        name: "London Stadium",
        capacity: 66000,
        city_name: "London",
        country_name: "England",
        map_coordinates: "null,null",
        country_code: "ENG",
      },
    },
  ],
};
