/* tslint:disable: object-literal-key-quotes object-literal-sort-keys*/
export const scheduleByDateMock = {
  generated_at: "2019-07-21T13:54:47+00:00",
  schema:
    "http://schemas.sportradar.com/bsa/soccer/v1/json/endpoints/soccer/schedule.json",
  sport_events: [
    {
      id: "sr:match:18440746",
      scheduled: "2019-09-01T10:15:00+00:00",
      start_time_tbd: false,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 5,
        phase: "regular season",
      },
      season: {
        id: "sr:season:67181",
        name: "Eredivisie 19/20",
        start_date: "2019-08-02",
        end_date: "2020-05-25",
        year: "19/20",
        tournament_id: "sr:tournament:37",
      },
      tournament: {
        id: "sr:tournament:37",
        name: "Eredivisie",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:35",
          name: "Netherlands",
          country_code: "NLD",
        },
      },
      competitors: [
        {
          id: "sr:competitor:2955",
          name: "FC Twente Enschede",
          country: "Netherlands",
          country_code: "NLD",
          abbreviation: "TWE",
          qualifier: "home",
        },
        {
          id: "sr:competitor:2948",
          name: "FC Utrecht",
          country: "Netherlands",
          country_code: "NLD",
          abbreviation: "FCU",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:584",
        name: "Grolsch Veste Stadium",
        capacity: 30205,
        city_name: "Enschede",
        country_name: "Netherlands",
        map_coordinates: "52.236667,6.837500",
        country_code: "NLD",
      },
    },
    {
      id: "sr:match:18382177",
      scheduled: "2019-09-01T11:00:00+00:00",
      start_time_tbd: false,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 8,
        phase: "regular season",
      },
      season: {
        id: "sr:season:67295",
        name: "Premier League 19/20",
        start_date: "2019-07-12",
        end_date: "2020-05-25",
        year: "19/20",
        tournament_id: "sr:tournament:203",
      },
      tournament: {
        id: "sr:tournament:203",
        name: "Premier League",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:21",
          name: "Russia",
          country_code: "RUS",
        },
      },
      competitors: [
        {
          id: "sr:competitor:7529",
          name: "FC Ural Yekaterinburg",
          country: "Russia",
          country_code: "RUS",
          abbreviation: "URA",
          qualifier: "home",
        },
        {
          id: "sr:competitor:34425",
          name: "FC Krasnodar",
          country: "Russia",
          country_code: "RUS",
          abbreviation: "KRA",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:5206",
        name: "Central Stadium",
        capacity: 35061,
        city_name: "Ekaterinburg",
        country_name: "Russia",
        map_coordinates: "56.832500,60.573611",
        country_code: "RUS",
      },
    },
    {
      id: "sr:match:18440748",
      scheduled: "2019-09-01T12:30:00+00:00",
      start_time_tbd: false,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 5,
        phase: "regular season",
      },
      season: {
        id: "sr:season:67181",
        name: "Eredivisie 19/20",
        start_date: "2019-08-02",
        end_date: "2020-05-25",
        year: "19/20",
        tournament_id: "sr:tournament:37",
      },
      tournament: {
        id: "sr:tournament:37",
        name: "Eredivisie",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:35",
          name: "Netherlands",
          country_code: "NLD",
        },
      },
      competitors: [
        {
          id: "sr:competitor:2960",
          name: "Sparta Rotterdam",
          country: "Netherlands",
          country_code: "NLD",
          abbreviation: "SPA",
          qualifier: "home",
        },
        {
          id: "sr:competitor:2953",
          name: "Ajax Amsterdam",
          country: "Netherlands",
          country_code: "NLD",
          abbreviation: "AJA",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:656",
        name: "Sparta Stadium Het Kasteel",
        capacity: 11026,
        city_name: "Rotterdam",
        country_name: "Netherlands",
        map_coordinates: "51.919485,4.433619",
        country_code: "NLD",
      },
    },
    {
      id: "sr:match:18440750",
      scheduled: "2019-09-01T12:30:00+00:00",
      start_time_tbd: false,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 5,
        phase: "regular season",
      },
      season: {
        id: "sr:season:67181",
        name: "Eredivisie 19/20",
        start_date: "2019-08-02",
        end_date: "2020-05-25",
        year: "19/20",
        tournament_id: "sr:tournament:37",
      },
      tournament: {
        id: "sr:tournament:37",
        name: "Eredivisie",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:35",
          name: "Netherlands",
          country_code: "NLD",
        },
      },
      competitors: [
        {
          id: "sr:competitor:2961",
          name: "Willem II Tilburg",
          country: "Netherlands",
          country_code: "NLD",
          abbreviation: "WIL",
          qualifier: "home",
        },
        {
          id: "sr:competitor:2959",
          name: "Feyenoord Rotterdam",
          country: "Netherlands",
          country_code: "NLD",
          abbreviation: "FEY",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:826",
        name: "Willem II Stadion",
        capacity: 14637,
        city_name: "Tilburg",
        country_name: "Netherlands",
        map_coordinates: "51.542778,5.066944",
        country_code: "NLD",
      },
    },
    {
      id: "sr:match:18600470",
      scheduled: "2019-09-01T12:30:00+00:00",
      start_time_tbd: false,
      status: "not_started",
      tournament_round: {
        type: "group",
        number: 6,
        phase: "regular season",
      },
      season: {
        id: "sr:season:66731",
        name: "First Division A 19/20",
        start_date: "2019-07-26",
        end_date: "2020-06-01",
        year: "19/20",
        tournament_id: "sr:tournament:38",
      },
      tournament: {
        id: "sr:tournament:38",
        name: "First Division A",
        sport: {
          id: "sr:sport:1",
          name: "Soccer",
        },
        category: {
          id: "sr:category:33",
          name: "Belgium",
          country_code: "BEL",
        },
      },
      competitors: [
        {
          id: "sr:competitor:2888",
          name: "Club Brugge",
          country: "Belgium",
          country_code: "BEL",
          abbreviation: "BRU",
          qualifier: "home",
        },
        {
          id: "sr:competitor:2890",
          name: "KRC Genk",
          country: "Belgium",
          country_code: "BEL",
          abbreviation: "GEN",
          qualifier: "away",
        },
      ],
      venue: {
        id: "sr:venue:1187",
        name: "Jan Breydel Stadium",
        capacity: 29975,
        city_name: "Bruges",
        country_name: "Belgium",
        map_coordinates: "51.193272,3.180583",
        country_code: "BEL",
      },
    },
  ],
};
