export default {
  generated_at: '2018-05-13T09:08:26+00:00',
  schema: 'http://schemas.sportradar.com/bsa/soccer/v1/json/endpoints/soccer/tournaments.json',
  tournaments: [
    {
      category: {
        id: 'sr:category:393',
        name: 'International Clubs',
      },
      current_season: {
        end_date: '2018-05-27',
        id: 'sr:season:41198',
        name: 'UEFA Champions League 17/18',
        start_date: '2017-06-27',
        year: '17/18',
      },
      id: 'sr:tournament:7',
      name: 'UEFA Champions League',
      season_coverage_info: {
        max_coverage_level: 'platinum',
        max_covered: 157,
        min_coverage_level: 'bronze',
        played: 220,
        scheduled: 291,
        seasonid: 'sr:season:41198',
      },
      sport: {
        id: 'sr:sport:1',
        name: 'Soccer',
      },
    },
    {
      category: {
        country_code: 'ESP',
        id: 'sr:category:32',
        name: 'Spain',
      },
      current_season: {
        end_date: '2018-05-21',
        id: 'sr:season:42556',
        name: 'LaLiga 17/18',
        start_date: '2017-08-18',
        year: '17/18',
      },
      id: 'sr:tournament:8',
      name: 'LaLiga',
      season_coverage_info: {
        max_coverage_level: 'platinum',
        max_covered: 368,
        min_coverage_level: 'silver',
        played: 369,
        scheduled: 385,
        seasonid: 'sr:season:42556',
      },
      sport: {
        id: 'sr:sport:1',
        name: 'Soccer',
      },
    },
    {
      category: {
        country_code: 'ENG',
        id: 'sr:category:1',
        name: 'England',
      },
      current_season: {
        end_date: '2018-05-14',
        id: 'sr:season:40942',
        name: 'Premier League 17/18',
        start_date: '2017-08-11',
        year: '17/18',
      },
      id: 'sr:tournament:17',
      name: 'Premier League',
      season_coverage_info: {
        max_coverage_level: 'platinum',
        max_covered: 370,
        min_coverage_level: 'silver',
        played: 380,
        scheduled: 397,
        seasonid: 'sr:season:40942',
      },
      sport: {
        id: 'sr:sport:1',
        name: 'Soccer',
      },
    },
    {
      category: {
        country_code: 'ITA',
        id: 'sr:category:31',
        name: 'Italy',
      },
      current_season: {
        end_date: '2018-05-21',
        id: 'sr:season:42720',
        name: 'Serie A 17/18',
        start_date: '2017-08-19',
        year: '17/18',
      },
      id: 'sr:tournament:23',
      name: 'Serie A',
      season_coverage_info: {
        max_coverage_level: 'platinum',
        max_covered: 362,
        min_coverage_level: 'silver',
        played: 373,
        scheduled: 392,
        seasonid: 'sr:season:42720',
      },
      sport: {
        id: 'sr:sport:1',
        name: 'Soccer',
      },
    },
    {
      category: {
        country_code: 'FRA',
        id: 'sr:category:7',
        name: 'France',
      },
      current_season: {
        end_date: '2018-06-01',
        id: 'sr:season:40958',
        name: 'Ligue 1 17/18',
        start_date: '2017-08-04',
        year: '17/18',
      },
      id: 'sr:tournament:34',
      name: 'Ligue 1',
      season_coverage_info: {
        max_coverage_level: 'platinum',
        max_covered: 371,
        min_coverage_level: 'silver',
        played: 373,
        scheduled: 384,
        seasonid: 'sr:season:40958',
      },
      sport: {
        id: 'sr:sport:1',
        name: 'Soccer',
      },
    },
    {
      category: {
        country_code: 'DEU',
        id: 'sr:category:30',
        name: 'Germany',
      },
      current_season: {
        end_date: '2018-05-22',
        id: 'sr:season:41576',
        name: 'Bundesliga 17/18',
        start_date: '2017-08-18',
        year: '17/18',
      },
      id: 'sr:tournament:35',
      name: 'Bundesliga',
      season_coverage_info: {
        max_coverage_level: 'platinum',
        max_covered: 306,
        min_coverage_level: 'platinum',
        played: 306,
        scheduled: 307,
        seasonid: 'sr:season:41576',
      },
      sport: {
        id: 'sr:sport:1',
        name: 'Soccer',
      },
    },
  ],
};
