export * from "./ITable";
export * from "./IFixture";
export * from "./IMatch";
export * from "./IMatchDetails";
export * from "./ISeason";
export * from "./ITournament";
export * from "./IRetriever";
export * from "./IUser";
export * from "./ILogo";
